# Generated by Django 4.1.2 on 2022-12-02 05:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_video_to),
        ),
    ]
