# Generated by Django 4.1.2 on 2022-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
